### ISSUE TITLE
issue in qty default - P1 issue

### ISSUE THREAD

**Issue by amarkalale** [IntentBrowser/localbiz#16]
I searched for sweet and got product listed.
I entered qty for sweet and clicked on proceed.
Now, it listed rice items in addition to sweet.

May be, I had entered qty for rice items in past. Now, I cant change qty of rice items to zero.

This default is real P1 issue. This is not a feature.

**Comment by venkatramanm** [comment]
Rice doesnot get added automatically but yes the changing quantity is not available at the checkout screen. Need to give that.
