### ISSUE TITLE
what's app integration slow on laptop.

### ISSUE THREAD

**Issue by amarkalale** [IntentBrowser/localbiz#4]
I placed one order. whatsapp got opened and took time to load all chats.

When I placed second order, I get error sating 'whatsapp already open" etc. Then, I closed window. Whatsapp message was in draft status. Then, I selected message and sent.

**Comment by venkatramanm** [comment]
Yeah what'sapp for desktop is a cluge. We should evangelized mainly on mobile

**Comment by venkatramanm** [comment]
Showing message for using on mobile
