### ISSUE TITLE
home delivery / store pickup

### ISSUE THREAD

**Issue by amarkalale** [IntentBrowser/localbiz#5]
Entire order will be wither home delivery or store pickup. It should not be for each product.
Also, we should configure by store, whether home delivery is provided or not.

**Comment by venkatramanm** [comment]
Config is by store only.  Currently we are displaying whether home delivery is available or not. How the order will be fulfilled will be figured by the sellers and buyers on what's app

**Comment by venkatramanm** [comment]
Moved the information fields like delivery support and cod support to header level in checkout screen
