### ISSUE TITLE
token / sequence number

### ISSUE THREAD

**Issue by amarkalale** [IntentBrowser/localbiz#8]
In whatsapp msg, also show one up seq#. It is one up by store and by date
20240823-001,20240823-002,...

**Comment by venkatramanm** [comment]
When multiple users are ordering, this can get mixed up unless centrally controlled.which can become a bottle neck. 

In whAts app world, is there a need for order number. That is assigned by the seller during billing.

**Comment by venkatramanm** [comment]
Added name and address on message..
